/****************************************************************************************/
/* Author   :   Mustafa Mahmoud Mustafa                                                 */
/* Date     :   3 March 2021                                                            */
/* Version  :   V01                                                                     */
/****************************************************************************************/

#ifndef STD_TYPES_H
#define STD_TYPES_H

typedef unsigned char       u8;
typedef unsigned short int  u16;
typedef unsigned long int   u32;
typedef signed char         s8;
typedef signed short int    s16;
typedef signed long int     s32;

#endif // STD_TYPES_H